spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/tw_mall
    username: root
    password: 123456
  jpa:
    show-sql: true
    database: mysql
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  jackson:
    default-property-inclusion: non_null
